### ISSUE TITLE
Elite Loot Crates

### ISSUE THREAD

**Issue by hazmattr** [Arkoudaphobia/ArkoudaphobiaConfig#108]
Elite Loot Crates now contain loot, but do not follow the bp loot system. Scrap, gun bodies, and other components are contained within elite loot crates.

**Comment by joshuaitguy** [comment]
This is by design, the fix that I put in place yesterday exempts the elite crates from the BP mod so it will use the default loot config for that item.  Unfortunately this is the best case fix at this time as loot tables are re-downloaded each time the BP mod is reloaded so any changes I make to the loot table are undone after a reload of the mod.
